### ISSUE TITLE
[依赖缺失]：nest项目依赖漏安装typeorm

### ISSUE THREAD

**Issue by CherishMvp** [zclzone/isme-nest-serve#1]
pnpm add typeorm

**Comment by zclzone** [comment]
typeorm其实是@nestjs/typeorm的一个peerDependencies，正常来说安装了@nestjs/typeorm是可以不用再重复安装typeorm的，在我本地及流水线构建环境中也确实没有任何问题，但由于某些原因好像有部分人确实没有安装上typeorm，所以我在 package.json 中补充了这个依赖

**Comment by CherishMvp** [comment]
你可能已经在其他项目中有安装过吧，我的node版本也挺高的，依赖安装好后确实会报typeorm错误。

**Comment by zclzone** [comment]
> 你可能已经在其他项目中有安装过吧，我的node版本也挺高的，依赖安装好后确实会报typeorm错误。

肯定不是这个原因的，因为我用云效流水线都没这个问题，不过依赖我已经加上了，你可以拉下最新的代码再装下依赖

**Comment by CherishMvp** [comment]
昨天加了就正常运行了
