### ISSUE TITLE
重启服务后数据库表异常

### ISSUE THREAD

**Issue by Ahspagh** [zclzone/isme-nest-serve#6]
创建schema 
本地启动的isme-nest-serve服务 
数据库连接成功
然后使用init.sql初始化表
数据正常
![image](https://github.com/zclzone/isme-nest-serve/assets/10679323/383433d6-eb60-4459-8acc-740998d30177)

重启服务 表就变成这样了
![image](https://github.com/zclzone/isme-nest-serve/assets/10679323/5f01ac4e-4b69-4b86-ad2a-19eaa748b5d7)

**Comment by zclzone** [comment]
typeOrm同步的问题，是不是改了实体，可以把.env文件下的DB_SYNC改成false

**Comment by Ahspagh** [comment]
DB_SYNC改成false 没有改entity还是会这样

**Comment by zclzone** [comment]
我搭了几个环境也没发现这个问题，想想是不是做了别的什么操作？

**Comment by zclzone** [comment]
未复现，先关闭 issue
